version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - "mongodb-data:/data/db"
      - "./mongo/init/:/docker-entrypoint-initdb.d/"
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE:
  sns-server:
    links:
      - mongo
    build:
      context: .
      dockerfile: ./docker/sns-server/Dockerfile
    container_name: sns-server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      DB_USERNAME:
      DB_PASSWORD:
      DB_HOSTNAME: mongo
      DB_PORT:
      DB_DATABASE:
      SERVER_PORT:
    command:
      - mongod
  sns-client:
    links:
      - mongo
      - sns-server
    build:
      context: .
      dockerfile: ./docker/sns-client/Dockerfile
    container_name: sns-client
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    environment:
      SERVER_PORT:
      CLIENT_PORT:
volumes:
  mongodb-data:
    driver: local