version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - "mongodb-data:/data/db"
      - "./mongo/init/:/docker-entrypoint-initdb.d/"
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE:
  sns-server:
    build:
      context: .
      dockerfile: ./docker/sns-server/Dockerfile
    container_name: sns-server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      DB_USERNAME:
      DB_PASSWORD:
      DB_HOSTNAME: mongo
      DB_PORT:
      DB_DATABASE:
      SERVER_PORT:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    # volumes:
    #   - ./nginx/:/etc/nginx/
    ports:
      - 8080:80
    environment:
      SERVER_PORT:
      SERVER_NAME:
    command: >
      /bin/sh -c "
      envsubst '
      $$SERVER_PORT $$SERVER_NAME
      ' < /etc/nginx/nginx.conf.template 
      > /etc/nginx/nginx.conf 
      && nginx -g 'daemon off;'"
volumes:
  mongodb-data:
    driver: local
