version: '3'
services:
  mongo:
    image: mongo
    build:
      context: .
      dockerfile: ./docker/mongo/Dockerfile
    container_name: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - "mongodb-data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
  sns-server:
    links:
      - mongo
    build:
      context: .
      dockerfile: ./docker/sns-server/Dockerfile
    container_name: sns-server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      DB_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      DB_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      DB_HOSTNAME: mongo
      DB_PORT: ${MONGO_PORT}
      DB_DATABASE: ${MONGO_INITDB_DATABASE}
      SERVER_PORT: ${SERVER_PORT}
    command:
      - mongod
  sns-client:
    links:
      - mongo
      - sns-server
    build:
      context: .
      dockerfile: ./docker/sns-client/Dockerfile
    container_name: sns-client
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    environment:
      SERVER_PORT: ${SERVER_PORT}
      CLIENT_PORT: ${CLIENT_PORT}
volumes:
  mongodb-data:
    driver: local